# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MAKMA Home' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MAKMA Home

	pod 'Firebase/Core'
	pod 'Firebase/Database’

  target 'MAKMA HomeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MAKMA HomeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
